name: "" #set whatevername you want to your github job
on: {} # set the events you would like to trigger this job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0 # use the latest version of the action
        with:
          email: panpana.weewong1@gmail.com # your heroku email
          api_key: f49aec11-7cdd-4f97-9f5c-dbf3226cd45d # your  heroku api key
          docker_compose_file: "./docker-compose.yml" # set the path to the folder where the docker-compose file is located
          heroku_apps: '[{"imagename":"app","app":"app1","apptype":"web"},{"imagename":"webserver","appname":"webserver","apptype":"webserver"},{"imagename":"db","appname":"db","apptype":"db"}]' # List of Docker Image name, Heroku app and Heroku app type
